apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bakerst

resources:
  - ../../nats
  - ../../qdrant
  - ../../brain
  - ../../task
  - ../../worker
  - ../../ui
  - ../../gateway
  - ../../sysadmin

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
