apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
  namespace: {{NAMESPACE}}
  labels:
    app: nats
data:
  nats.conf: |
    listen: 0.0.0.0:4222

    jetstream {
      store_dir: /data/jetstream
      max_mem: 128M
      max_file: 512M
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: {{NAMESPACE}}
  labels:
    app: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats:2.10-alpine
          args: ["-c", "/etc/nats/nats.conf"]
          ports:
            - containerPort: 4222
              name: client
          volumeMounts:
            - name: config
              mountPath: /etc/nats
              readOnly: true
            - name: jetstream-data
              mountPath: /data/jetstream
          readinessProbe:
            tcpSocket:
              port: 4222
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 4222
            initialDelaySeconds: 15
            periodSeconds: 30
            failureThreshold: 3
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: config
          configMap:
            name: nats-config
        - name: jetstream-data
          emptyDir:
            sizeLimit: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: {{NAMESPACE}}
spec:
  selector:
    app: nats
  ports:
    - port: 4222
      targetPort: 4222
      name: client
