/**
 * Release Manifest types — contract between the CI pipeline and the SysAdmin pod.
 *
 * The release manifest is generated by the GitHub Actions release workflow and
 * consumed by the SysAdmin pod to orchestrate deployments and updates.
 */

// ---------------------------------------------------------------------------
// Image entry
// ---------------------------------------------------------------------------

export interface ReleaseManifestImage {
  /** Component name (e.g., "brain", "worker", "ui", "gateway", "sysadmin") */
  component: string;
  /** Full image reference (e.g., "ghcr.io/the-baker-street-project/bakerst-brain:1.2.0") */
  image: string;
  /** SemVer version of this component */
  version: string;
  /** Image digest (e.g., "sha256:abc123...") */
  digest: string;
  /** Whether this component is required for a functional deployment */
  required: boolean;
}

// ---------------------------------------------------------------------------
// Prompt entry
// ---------------------------------------------------------------------------

export interface ReleaseManifestPrompt {
  /** SemVer version of this prompt */
  version: string;
  /** SHA-256 content hash for integrity verification */
  contentHash: string;
  /** Inline prompt content (only for sysadmin-runtime, others are in the OS configmap) */
  content?: string;
}

// ---------------------------------------------------------------------------
// Secret requirement
// ---------------------------------------------------------------------------

export interface ReleaseManifestSecret {
  /** Secret key name (e.g., "ANTHROPIC_API_KEY") */
  key: string;
  /** Human-readable description shown to the user during setup */
  description: string;
  /** Whether this secret is required for deployment */
  required: boolean;
  /** Input type for the terminal UI */
  inputType: 'text' | 'secret' | 'choice';
  /** Which K8s secrets this value should be written to */
  targetSecrets: string[];
  /** Valid choices (when inputType is "choice") */
  choices?: string[];
}

// ---------------------------------------------------------------------------
// Optional feature
// ---------------------------------------------------------------------------

export interface ReleaseManifestFeature {
  /** Unique feature identifier */
  id: string;
  /** Human-readable name */
  name: string;
  /** Description shown to the user */
  description: string;
  /** Whether this feature is enabled by default */
  defaultEnabled: boolean;
  /** Secret keys required by this feature */
  secrets: string[];
}

// ---------------------------------------------------------------------------
// Top-level manifest
// ---------------------------------------------------------------------------

export interface ReleaseManifest {
  /** Schema version for forward compatibility */
  schemaVersion: number;
  /** Release version (e.g., "1.2.3") */
  version: string;
  /** ISO 8601 release date */
  date: string;
  /** Minimum SysAdmin version required to process this manifest */
  minSysadminVersion: string;
  /** Human-readable release notes */
  releaseNotes: string;

  /** Container images in this release */
  images: ReleaseManifestImage[];

  /** Prompt files and their versions */
  prompts: Record<string, ReleaseManifestPrompt>;

  /** Secrets the SysAdmin should collect during deploy */
  requiredSecrets: ReleaseManifestSecret[];

  /** Optional features the user can enable */
  optionalFeatures: ReleaseManifestFeature[];

  /** Default configuration values */
  defaults: {
    agentName: string;
    namespace: string;
    resourceProfile: 'minimal' | 'standard' | 'performance';
  };

  /** Image digest checksums for integrity verification */
  checksums: Record<string, string>;
}

// ---------------------------------------------------------------------------
// SysAdmin state types
// ---------------------------------------------------------------------------

export type SysAdminState = 'deploy' | 'runtime' | 'update' | 'shutdown';

export interface SysAdminPersistedState {
  /** Current state machine state */
  state: SysAdminState;
  /** Currently deployed release version */
  deployedVersion?: string;
  /** Timestamp of last successful deployment */
  deployedAt?: string;
  /** Last health check result */
  lastHealthCheck?: HealthCheckResult;
  /** Ring buffer of recent health check results (max 100) */
  healthHistory: HealthCheckResult[];
  /** Active runtime prompt content hash */
  runtimePromptHash?: string;
}

export interface HealthCheckResult {
  /** ISO 8601 timestamp */
  timestamp: string;
  /** Overall health status */
  healthy: boolean;
  /** Per-component health status */
  components: ComponentHealth[];
}

export interface ComponentHealth {
  /** Component name (e.g., "brain", "worker") */
  name: string;
  /** Whether this component is healthy */
  healthy: boolean;
  /** Number of ready replicas */
  readyReplicas: number;
  /** Number of desired replicas */
  desiredReplicas: number;
  /** Current image reference */
  image?: string;
  /** Error message if unhealthy */
  error?: string;
}
